// <auto-generated />
using System;
using DataAccess.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(AtmoContext))]
    [Migration("20200408192852_newSeed")]
    partial class newSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Archived");

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime?>("EditDate");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 69,
                            Archived = false,
                            Content = "69",
                            CreationDate = new DateTime(2020, 4, 8, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(9140)
                        },
                        new
                        {
                            Id = 1,
                            Archived = false,
                            Content = "Test Ticket number 1",
                            CreationDate = new DateTime(2020, 4, 7, 21, 28, 51, 873, DateTimeKind.Local).AddTicks(6950)
                        },
                        new
                        {
                            Id = 16,
                            Archived = true,
                            Content = "Test archived Ticket number 1",
                            CreationDate = new DateTime(2020, 3, 8, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8217)
                        },
                        new
                        {
                            Id = 2,
                            Archived = false,
                            Content = "Test Ticket number 2",
                            CreationDate = new DateTime(2020, 4, 6, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8266)
                        },
                        new
                        {
                            Id = 17,
                            Archived = true,
                            Content = "Test archived Ticket number 2",
                            CreationDate = new DateTime(2020, 2, 8, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8273)
                        },
                        new
                        {
                            Id = 3,
                            Archived = false,
                            Content = "Test Ticket number 3",
                            CreationDate = new DateTime(2020, 4, 5, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8280)
                        },
                        new
                        {
                            Id = 18,
                            Archived = true,
                            Content = "Test archived Ticket number 3",
                            CreationDate = new DateTime(2020, 1, 8, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8293)
                        },
                        new
                        {
                            Id = 4,
                            Archived = false,
                            Content = "Test Ticket number 4",
                            CreationDate = new DateTime(2020, 4, 4, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8299)
                        },
                        new
                        {
                            Id = 19,
                            Archived = true,
                            Content = "Test archived Ticket number 4",
                            CreationDate = new DateTime(2019, 12, 8, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8305)
                        },
                        new
                        {
                            Id = 5,
                            Archived = false,
                            Content = "Test Ticket number 5",
                            CreationDate = new DateTime(2020, 4, 3, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8312)
                        },
                        new
                        {
                            Id = 20,
                            Archived = true,
                            Content = "Test archived Ticket number 5",
                            CreationDate = new DateTime(2019, 11, 8, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8318)
                        },
                        new
                        {
                            Id = 6,
                            Archived = false,
                            Content = "Test Ticket number 6",
                            CreationDate = new DateTime(2020, 4, 2, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8324)
                        },
                        new
                        {
                            Id = 21,
                            Archived = true,
                            Content = "Test archived Ticket number 6",
                            CreationDate = new DateTime(2019, 10, 8, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8330)
                        },
                        new
                        {
                            Id = 7,
                            Archived = false,
                            Content = "Test Ticket number 7",
                            CreationDate = new DateTime(2020, 4, 1, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8336)
                        },
                        new
                        {
                            Id = 22,
                            Archived = true,
                            Content = "Test archived Ticket number 7",
                            CreationDate = new DateTime(2019, 9, 8, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8341)
                        },
                        new
                        {
                            Id = 8,
                            Archived = false,
                            Content = "Test Ticket number 8",
                            CreationDate = new DateTime(2020, 3, 31, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8347)
                        },
                        new
                        {
                            Id = 23,
                            Archived = true,
                            Content = "Test archived Ticket number 8",
                            CreationDate = new DateTime(2019, 8, 8, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8353)
                        },
                        new
                        {
                            Id = 9,
                            Archived = false,
                            Content = "Test Ticket number 9",
                            CreationDate = new DateTime(2020, 3, 30, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8359)
                        },
                        new
                        {
                            Id = 24,
                            Archived = true,
                            Content = "Test archived Ticket number 9",
                            CreationDate = new DateTime(2019, 7, 8, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8365)
                        },
                        new
                        {
                            Id = 10,
                            Archived = false,
                            Content = "Test Ticket number 10",
                            CreationDate = new DateTime(2020, 3, 29, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8371)
                        },
                        new
                        {
                            Id = 25,
                            Archived = true,
                            Content = "Test archived Ticket number 10",
                            CreationDate = new DateTime(2019, 6, 8, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8377)
                        },
                        new
                        {
                            Id = 11,
                            Archived = false,
                            Content = "Test Ticket number 11",
                            CreationDate = new DateTime(2020, 3, 28, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8383)
                        },
                        new
                        {
                            Id = 26,
                            Archived = true,
                            Content = "Test archived Ticket number 11",
                            CreationDate = new DateTime(2019, 5, 8, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8389)
                        },
                        new
                        {
                            Id = 12,
                            Archived = false,
                            Content = "Test Ticket number 12",
                            CreationDate = new DateTime(2020, 3, 27, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8395)
                        },
                        new
                        {
                            Id = 27,
                            Archived = true,
                            Content = "Test archived Ticket number 12",
                            CreationDate = new DateTime(2019, 4, 8, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8400)
                        },
                        new
                        {
                            Id = 13,
                            Archived = false,
                            Content = "Test Ticket number 13",
                            CreationDate = new DateTime(2020, 3, 26, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8406)
                        },
                        new
                        {
                            Id = 28,
                            Archived = true,
                            Content = "Test archived Ticket number 13",
                            CreationDate = new DateTime(2019, 3, 8, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8412)
                        },
                        new
                        {
                            Id = 14,
                            Archived = false,
                            Content = "Test Ticket number 14",
                            CreationDate = new DateTime(2020, 3, 25, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8418)
                        },
                        new
                        {
                            Id = 29,
                            Archived = true,
                            Content = "Test archived Ticket number 14",
                            CreationDate = new DateTime(2019, 2, 8, 21, 28, 51, 876, DateTimeKind.Local).AddTicks(8423)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
